name: tuisong

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/15 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      # Runs a single command using the runners shell
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip install faker -i https://pypi.tuna.tsinghua.edu.cn/simple
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python main.py
          python file.py
        env:
          GITHUB_API_URL: https://api.github.com

